# Generated by Django 4.1.2 on 2022-12-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_catigories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catigories',
            new_name='Categories',
        ),
    ]
