# Generated by Django 4.1.2 on 2022-12-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_desctription_products_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
